# Generated by Django 3.2.7 on 2022-07-10 20:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('profiles', '0005_profile_is_author'),
    ]

    operations = [
        migrations.CreateModel(
            name='Author',
            fields=[
                ('profile_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='profiles.profile')),
            ],
            options={
                'abstract': False,
            },
            bases=('profiles.profile',),
        ),
    ]
