# Generated by Django 3.2.7 on 2022-07-17 20:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0006_alter_article_title'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='image1',
            field=models.ImageField(blank=True, null=True, upload_to='apps/articles_images/'),
        ),
        migrations.AlterField(
            model_name='article',
            name='image2',
            field=models.ImageField(blank=True, null=True, upload_to='apps/articles_images/'),
        ),
    ]
